# Generated by Django 4.2.1 on 2025-05-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_age_alter_userprofile_age_and_more'),
        ('accounts', '0009_alter_userportfolio_options_and_more'),
    ]

    operations = [
    ]
