# Generated by Django 4.2.1 on 2025-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20250526_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='etc_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
