# Generated by Django 4.2.1 on 2025-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialcompany_financialproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproduct',
            name='max_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='name',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='product_type',
            field=models.CharField(choices=[('deposit', '정기예금'), ('savings', '적금'), ('jeonse', '전세자금대출'), ('credit', '개인신용대출')], default='deposit', max_length=20),
        ),
    ]
