# Generated by Django 4.2.1 on 2025-05-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financialproduct_max_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialproduct',
            name='product_type',
            field=models.CharField(choices=[('deposit', '정기예금'), ('savings', '적금'), ('rent', '전세자금대출'), ('credit', '개인신용대출')], default='deposit', max_length=20),
        ),
    ]
