# Generated by Django 4.2.1 on 2025-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_creditloanproduct_depositproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditloanproduct',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='creditloanproduct',
            name='fin_co_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='fin_co_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='join_deny',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='max_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renthouseloanproduct',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='renthouseloanproduct',
            name='fin_co_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='fin_co_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='join_deny',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='max_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='renthouseloanproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='renthouseloanproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
