# Generated by Django 5.2.1 on 2025-05-18 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSavings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=100)),
                ('productCode', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=100)),
                ('etcNote', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
