# Generated by Django 4.2.1 on 2025-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_creditloanproduct_dcls_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditloanproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='renthouseloanproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=20),
        ),
    ]
