# Generated by Django 4.2.1 on 2025-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_creditloanproduct_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproduct',
            name='fin_prdt_cd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creditloanproduct',
            name='fin_prdt_cd',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_prdt_cd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='renthouseloanproduct',
            name='fin_prdt_cd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_cd',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
