# Generated by Django 4.2.1 on 2025-05-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_creditloanproduct_intr_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditloanproduct',
            old_name='intr_rate',
            new_name='lend_rate_avg',
        ),
        migrations.RenameField(
            model_name='renthouseloanproduct',
            old_name='intr_rate',
            new_name='crdt_grad_avg',
        ),
        migrations.RemoveField(
            model_name='creditloanproduct',
            name='intr_rate2',
        ),
        migrations.RemoveField(
            model_name='creditloanproduct',
            name='intr_rate_type',
        ),
        migrations.RemoveField(
            model_name='creditloanproduct',
            name='intr_rate_type_nm',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='max_interest_rate',
        ),
        migrations.RemoveField(
            model_name='renthouseloanproduct',
            name='intr_rate2',
        ),
        migrations.RemoveField(
            model_name='renthouseloanproduct',
            name='intr_rate_type',
        ),
        migrations.RemoveField(
            model_name='renthouseloanproduct',
            name='intr_rate_type_nm',
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='crdt_grad_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='intr_rate2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='financialproduct',
            name='lend_rate_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
