# Generated by Django 4.2.1 on 2025-05-23 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='financial_goal',
            field=models.CharField(choices=[('saving', 'Saving'), ('investment', 'Investment'), ('retirement', 'Retirement')], default='saving', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='risk_tolerance',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=100)),
                ('productType', models.CharField(max_length=100)),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prePaymentPenalty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('joinedAt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
