# Generated by Django 4.2.1 on 2025-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_age_userprofile_financial_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='deletedAt',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='income_level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
