# Generated by Django 4.2.1 on 2025-05-24 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_creditloanproduct_fin_prdt_cd_and_more'),
        ('accounts', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='bankName',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='interestRate',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='prePaymentPenalty',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='productType',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='is_interested',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='finance.financialproduct'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='saved_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='saved_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='saved_pre_payment_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='saved_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='saved_product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
