# Generated by Django 4.2.1 on 2025-05-24 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_creditloanproduct_fin_prdt_cd_and_more'),
        ('accounts', '0007_remove_userportfolio_bankname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='is_interested',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='saved_bank_name',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='saved_interest_rate',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='saved_pre_payment_penalty',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='saved_product_name',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='saved_product_type',
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='joinedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='finance.financialproduct'),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
