# Generated by Django 4.2.1 on 2025-05-25 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_rename_intr_rate_creditloanproduct_lend_rate_avg_and_more'),
        ('accounts', '0008_remove_userportfolio_is_interested_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userportfolio',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='joinedAt',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='product',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='deposit_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.depositproduct'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='product_type',
            field=models.CharField(choices=[('deposit', '예금'), ('saving', '적금')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='save_trm',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='saving_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.savingproduct'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='special_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
